development:
    GOOGLE_CLIENT_ID: 286769101745-62bfeoo4s3tpe59casgl3kbjq1ugk3lm.apps.googleusercontent.com
    GOOGLE_CLIENT_SECRET: IyJgG7ujfEs_3eTddFRKx5Gv

native:
    GOOGLE_CLIENT_ID: 286769101745-uft1t84cg15e981m5dc2hln96qb7olfl.apps.googleusercontent.com
    GOOGLE_CLIENT_SECRET: Zn6IpXs7lNKc8MQxTF4TqGds

production:
    GOOGLE_CLIENT_ID: 286769101745-us63v42ckm72batbvg3o6s0kgf2malld.apps.googleusercontent.com
    GOOGLE_CLIENT_SECRET: MvYDxMDC_mJhtA5yWUkFM4aA